### ISSUE TITLE
Support for plot_tree

### ISSUE THREAD

**Issue by inspire22** [ankane/xgboost-ruby#10]
Hi!

Thanks again for this :) Does it include the plot_tree stuff in the python library? I don't think so, but it's hard to tell what's handed off to the XGBoost library...

Otherwise, I could maybe try and load the saved model into python and plot it from there?

Thanks!

**Comment by ankane** [comment]
Hi @inspire22, plotting isn't implemented, but you can load models into Python.

```python
import matplotlib.pyplot as plt
import xgboost as xgb

bst = xgb.Booster(model_file='model.bin')
xgb.plot_tree(bst)

plt.show()
```
